apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-theme-minimal-setting
spec:
  forms:
    - group: info
      label: 站点信息
      formSchema:
        - $formkit: text
          name: siteTitle
          label: 网站标题
          value:
        - $formkit: text
          name: siteSubtitle
          label: 网站副标题
          value:
        - $formkit: group
          name: favicon
          value:
          children:
            - $formkit: attachment
              name: ico
              label: 网站logo(推荐.ico格式，16x16)
        - $formkit: group
          name: profile
          value:
          children:
            - $formkit: attachment
              name: logo
              label: 头像
        - $formkit: group
          name: login
          value:
          children:
            - $formkit: attachment
              name: loginImage
              label: 登录页面logo
        - $formkit: text
          name: profileName
          label: 用户名
          value:
        - $formkit: text
          name: bio
          label: 个性签名
          value:
    - group: sidebar
      label: 侧边栏
      formSchema:
        - $formkit: repeater
          name: widgets
          label: 小部件
          value:
            - value: summary
            - value: categories
            - value: tags
          children:
            - $formkit: select
              name: value
              label: 组件
              options:
                - label: 文章目录
                  value: summary
                - label: 文章分类
                  value: categories
                - label: 文章标签
                  value: tags
        - $formkit: repeater
          name: social_media
          label: 社交媒体
          value: []
          children:
            - $formkit: select
              name: icon
              label: 图标
              options:
                - label: 电子邮箱
                  value: hugeicons--mail-02
                - label: Telegram
                  value: hugeicons--telegram
                - label: Discord
                  value: qlementine-icons--discord-16
                - label: GitHub
                  value: hugeicons--github
                - label: RSS
                  value: lucide--rss
            - $formkit: text
              name: url
              label: 链接
              validation: "required"
    - group: article_setting
      label: 文章设置
      formSchema:
        - $formkit: checkbox
          name: outdated_notice
          id: outdated_notice
          label: 文章过时提示框
          value: false

        - $formkit: number
          if: "$get(outdated_notice).value"
          name: choiceMonths
          label: 过时提示阈值（月）
          placeholder: 文章过时的月数
          value:
          validation: "number|required"
    - group: site_style
      label: 网站样式
      formSchema:
        - $formkit: select
          name: font
          value: Comic-Sans-MS
          label: 字体
          options:
            - label: Comic-Sans-MS
              value: Comic-Sans-MS
            - label: 手写体
              value: 手写体
